# Generated by Django 3.2.12 on 2022-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='phone_number',
            field=models.CharField(default='+998999999999', max_length=25),
            preserve_default=False,
        ),
    ]
