# Generated by Django 3.2.12 on 2022-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
